import {
    ArticleCategoryEnum,
    CollectionVisibilityEnum,
    ContentTypeEnum,
    HistoryTypeEnum,
    UserRoleEnum,
    WatchStatusEnum,
} from '@hikka/client';

import { FeedItem } from './types';

const mockUser = (username: string, avatar?: string) => ({
    reference: `user-${username}`,
    updated: null,
    created: Date.now() / 1000 - 86400 * 30,
    description: null,
    username,
    cover: null,
    active: true,
    avatar: avatar || 'https://api.hikka.io/avatar/default',
    role: UserRoleEnum.USER,
});

const now = Math.floor(Date.now() / 1000);

export const MOCK_FEED_DATA: FeedItem[] = [
    {
        reference: 'feed-history-1',
        created: now - 3600 * 19,
        data_type: ContentTypeEnum.HISTORY,
        data: {
            reference: 'history-1',
            created: now - 3600 * 19,
            updated: now - 3600 * 19,
            user: mockUser('Okashi'),
            history_type: HistoryTypeEnum.WATCH,
            content: {
                data_type: ContentTypeEnum.ANIME,
                title_ua: 'Моя героїська академія - 2 сезон',
                title_en: 'My Hero Academia Season 2',
                title_ja: 'Boku no Hero Academia 2nd Season',
                slug: 'boku-no-hero-academia-2nd-season',
                image: 'https://cdn.hikka.io/hikka/placeholders/anime.svg',
                scored_by: 0,
                score: 0,
                media_type: null,
                episodes_released: 25,
                episodes_total: 25,
                status: null,
                year: 2017,
                season: null,
                watch: [],
                translated_ua: false,
                genres: [],
                synonyms: [],
                title: 'Моя героїська академія - 2 сезон',
            } as any,
            data: {
                after: {
                    score: 9,
                    status: WatchStatusEnum.WATCHING,
                    episodes: 20,
                    rewatches: 0,
                },
                before: {
                    score: null,
                    status: WatchStatusEnum.WATCHING,
                    episodes: 0,
                    rewatches: 0,
                },
                new_watch: false,
            },
        },
    },
    {
        reference: 'feed-collection-1',
        created: now - 86400 * 2,
        data_type: ContentTypeEnum.COLLECTION,
        data: {
            data_type: ContentTypeEnum.COLLECTION,
            visibility: CollectionVisibilityEnum.PUBLIC,
            author: mockUser('dunno'),
            labels_order: [],
            created: now - 86400 * 2,
            updated: now - 86400 * 2,
            comments_count: 15,
            content_type: ContentTypeEnum.ANIME,
            description: '',
            vote_score: 6,
            tags: ['огляд', 'тест2', 'тест3'],
            reference: 'collection-1',
            my_score: 0,
            spoiler: false,
            entries: 19,
            title: 'Супер сильні гг / OP MCs',
            nsfw: false,
            collection: Array.from({ length: 5 }, (_, i) => ({
                comment: null,
                label: null,
                content_type: ContentTypeEnum.ANIME,
                order: i,
                content: {
                    data_type: ContentTypeEnum.ANIME,
                    title_ua: `Аніме ${i + 1}`,
                    title_en: `Anime ${i + 1}`,
                    title_ja: `Anime ${i + 1}`,
                    slug: `anime-${i + 1}`,
                    image: 'https://cdn.hikka.io/hikka/placeholders/anime.svg',
                    scored_by: 0,
                    score: 0,
                    media_type: null,
                    episodes_released: 12,
                    episodes_total: 12,
                    status: null,
                    year: 2024,
                    season: null,
                    watch: [],
                    translated_ua: false,
                    genres: [],
                    synonyms: [],
                    title: `Аніме ${i + 1}`,
                } as any,
            })),
        },
    },
    {
        reference: 'feed-article-1',
        created: now - 3600 * 19,
        data_type: ContentTypeEnum.ARTICLE,
        data: {
            data_type: ContentTypeEnum.ARTICLE,
            author: mockUser('Okashi'),
            tags: [
                { name: 'zenmarket', content_count: 5 },
                { name: 'японія', content_count: 3 },
            ],
            created: now - 3600 * 19,
            updated: now - 3600 * 19,
            comments_count: 15,
            vote_score: 2,
            my_score: 0,
            category: ArticleCategoryEnum.ORIGINAL,
            trusted: false,
            draft: false,
            views: 0,
            title: 'Огляд Cup Noodles з Японії',
            slug: 'oglyad-cup-noodles-z-yaponiyi',
            content: {
                data_type: ContentTypeEnum.ANIME,
                title_ua: 'Моя героїська академія - 2 сезон',
                title_en: 'My Hero Academia Season 2',
                title_ja: 'Boku no Hero Academia 2nd Season',
                slug: 'boku-no-hero-academia-2nd-season',
                image: 'https://cdn.hikka.io/hikka/placeholders/anime.svg',
                scored_by: 0,
                score: 0,
                media_type: null,
                episodes_released: 25,
                episodes_total: 25,
                status: null,
                year: 2017,
                season: null,
                watch: [],
                translated_ua: false,
                genres: [],
                synonyms: [],
                title: 'Моя героїська академія - 2 сезон',
            } as any,
            preview: [
                {
                    type: 'p',
                    children: [
                        {
                            text: '«Якось я загорівся бажанням придбати щось з Японії, буквально будь-що, аби тільки реально з країни, де сходить то анімешне сонце...» Власне, про це буде ця стаття, тож беріть щось смачненьке, гарно всаджуйтесь в крісло і погнали досліджувати.',
                        },
                    ],
                },
            ],
        },
    },
    {
        reference: 'feed-comment-1',
        created: now - 3600 * 19,
        data_type: ContentTypeEnum.COMMENT,
        data: {
            replies: [],
            total_replies: 0,
            updated: now - 3600 * 19,
            created: now - 3600 * 19,
            author: mockUser('Okashi'),
            parent: null,
            content_type: ContentTypeEnum.ANIME,
            is_editable: false,
            text: 'Це однозначно краще ніж перший сезон. Флешбеків менше, а боїв більше.',
            vote_score: 2,
            reference: 'comment-1',
            my_score: 0,
            preview: {
                slug: 'boku-no-hero-academia-2nd-season',
                title: 'Моя героїська академія - 2 сезон',
            },
            hidden: false,
            depth: 0,
        },
    },
    {
        reference: 'feed-history-2',
        created: now - 3600 * 24,
        data_type: ContentTypeEnum.HISTORY,
        data: {
            reference: 'history-2',
            created: now - 3600 * 24,
            updated: now - 3600 * 24,
            user: mockUser('TestUser'),
            history_type: HistoryTypeEnum.WATCH,
            content: {
                data_type: ContentTypeEnum.ANIME,
                title_ua: 'Атака Титанів',
                title_en: 'Attack on Titan',
                title_ja: 'Shingeki no Kyojin',
                slug: 'shingeki-no-kyojin',
                image: 'https://cdn.hikka.io/hikka/placeholders/anime.svg',
                scored_by: 0,
                score: 0,
                media_type: null,
                episodes_released: 25,
                episodes_total: 25,
                status: null,
                year: 2013,
                season: null,
                watch: [],
                translated_ua: false,
                genres: [],
                synonyms: [],
                title: 'Атака Титанів',
            } as any,
            data: {
                after: {
                    score: 8,
                    status: WatchStatusEnum.COMPLETED,
                    episodes: 25,
                    rewatches: 0,
                },
                before: {
                    score: null,
                    status: WatchStatusEnum.WATCHING,
                    episodes: 20,
                    rewatches: 0,
                },
                new_watch: false,
            },
        },
    },
    {
        reference: 'feed-article-2',
        created: now - 86400 * 3,
        data_type: ContentTypeEnum.ARTICLE,
        data: {
            data_type: ContentTypeEnum.ARTICLE,
            author: mockUser('WriterPro'),
            tags: [
                { name: 'рекомендації', content_count: 10 },
                { name: 'топ', content_count: 8 },
            ],
            created: now - 86400 * 3,
            updated: now - 86400 * 3,
            comments_count: 8,
            vote_score: 12,
            my_score: 0,
            category: ArticleCategoryEnum.REVIEWS,
            trusted: false,
            draft: false,
            views: 150,
            title: 'Топ-10 аніме зимового сезону 2025',
            slug: 'top-10-anime-zymovogo-sezonu-2025',
            content: null,
            preview: [
                {
                    type: 'p',
                    children: [
                        {
                            text: 'Зимовий сезон 2025 року виявився надзвичайно багатим на якісні тайтли. У цій статті ми розглянемо десять найкращих аніме, які точно варто подивитися.',
                        },
                    ],
                },
            ],
        },
    },
];
