FROM node:20.15.1-alpine3.20 AS base

FROM base AS deps
RUN apk add --no-cache libc6-compat

WORKDIR /app

COPY package.json ./
RUN corepack enable yarn && yarn install

RUN yarn add @next/swc-linux-x64-gnu @next/swc-linux-x64-musl


COPY . .

CMD ["yarn", "dev"]