/* prettier-ignore-start */
/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// It is auto-updated on each build.

import { createFileRoute, createRootRoute } from '@tanstack/react-router'

export const routeTree = createRootRoute()
