/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PagesRouteImport } from './routes/_pages'
import { Route as PagesIndexRouteImport } from './routes/_pages/index'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as AuthGoogleRouteImport } from './routes/auth/google'
import { Route as PagesSettingsRouteImport } from './routes/_pages/settings'
import { Route as PagesScheduleRouteImport } from './routes/_pages/schedule'
import { Route as PagesOauthRouteImport } from './routes/_pages/oauth'
import { Route as PagesAuthRouteImport } from './routes/_pages/_auth'
import { Route as ApiSitemapIndexRouteImport } from './routes/api/sitemap/index'
import { Route as PagesSettingsIndexRouteImport } from './routes/_pages/settings/index'
import { Route as PagesPeopleIndexRouteImport } from './routes/_pages/people/index'
import { Route as PagesNovelIndexRouteImport } from './routes/_pages/novel/index'
import { Route as PagesMangaIndexRouteImport } from './routes/_pages/manga/index'
import { Route as PagesEditIndexRouteImport } from './routes/_pages/edit/index'
import { Route as PagesCollectionsIndexRouteImport } from './routes/_pages/collections/index'
import { Route as PagesCharactersIndexRouteImport } from './routes/_pages/characters/index'
import { Route as PagesArticlesIndexRouteImport } from './routes/_pages/articles/index'
import { Route as PagesAnimeIndexRouteImport } from './routes/_pages/anime/index'
import { Route as AuthResetTokenRouteImport } from './routes/auth/reset.$token'
import { Route as AuthActivateTokenRouteImport } from './routes/auth/activate.$token'
import { Route as ApiSitemapNovelRouteImport } from './routes/api/sitemap/novel'
import { Route as ApiSitemapMangaRouteImport } from './routes/api/sitemap/manga'
import { Route as ApiSitemapAnimeRouteImport } from './routes/api/sitemap/anime'
import { Route as ApiOgNovelRouteImport } from './routes/api/og/novel'
import { Route as ApiOgMangaRouteImport } from './routes/api/og/manga'
import { Route as ApiOgAnimeRouteImport } from './routes/api/og/anime'
import { Route as PagesUUsernameRouteImport } from './routes/_pages/u/$username'
import { Route as PagesSettingsSecurityRouteImport } from './routes/_pages/settings/security'
import { Route as PagesSettingsProfileRouteImport } from './routes/_pages/settings/profile'
import { Route as PagesSettingsNotificationsRouteImport } from './routes/_pages/settings/notifications'
import { Route as PagesSettingsListRouteImport } from './routes/_pages/settings/list'
import { Route as PagesSettingsCustomizationRouteImport } from './routes/_pages/settings/customization'
import { Route as PagesSettingsApplicationsRouteImport } from './routes/_pages/settings/applications'
import { Route as PagesPeopleSlugRouteImport } from './routes/_pages/people/$slug'
import { Route as PagesNovelSlugRouteImport } from './routes/_pages/novel/$slug'
import { Route as PagesMangaSlugRouteImport } from './routes/_pages/manga/$slug'
import { Route as PagesEditNewRouteImport } from './routes/_pages/edit/new'
import { Route as PagesEditContentRouteImport } from './routes/_pages/edit/content'
import { Route as PagesEditEditIdRouteImport } from './routes/_pages/edit/$editId'
import { Route as PagesCommentsLatestRouteImport } from './routes/_pages/comments/latest'
import { Route as PagesCollectionsNewRouteImport } from './routes/_pages/collections/new'
import { Route as PagesCollectionsReferenceRouteImport } from './routes/_pages/collections/$reference'
import { Route as PagesCharactersSlugRouteImport } from './routes/_pages/characters/$slug'
import { Route as PagesArticlesNewRouteImport } from './routes/_pages/articles/new'
import { Route as PagesArticlesSlugRouteImport } from './routes/_pages/articles/$slug'
import { Route as PagesAnimeSlugRouteImport } from './routes/_pages/anime/$slug'
import { Route as PagesAuthSignupRouteImport } from './routes/_pages/_auth/signup'
import { Route as PagesAuthResetRouteImport } from './routes/_pages/_auth/reset'
import { Route as PagesAuthLoginRouteImport } from './routes/_pages/_auth/login'
import { Route as PagesUUsernameIndexRouteImport } from './routes/_pages/u/$username/index'
import { Route as PagesPeopleSlugIndexRouteImport } from './routes/_pages/people/$slug/index'
import { Route as PagesNovelSlugIndexRouteImport } from './routes/_pages/novel/$slug/index'
import { Route as PagesMangaSlugIndexRouteImport } from './routes/_pages/manga/$slug/index'
import { Route as PagesEditEditIdIndexRouteImport } from './routes/_pages/edit/$editId/index'
import { Route as PagesCollectionsReferenceIndexRouteImport } from './routes/_pages/collections/$reference/index'
import { Route as PagesCharactersSlugIndexRouteImport } from './routes/_pages/characters/$slug/index'
import { Route as PagesArticlesSlugIndexRouteImport } from './routes/_pages/articles/$slug/index'
import { Route as PagesAnimeSlugIndexRouteImport } from './routes/_pages/anime/$slug/index'
import { Route as PagesUUsernameListRouteImport } from './routes/_pages/u/$username/list'
import { Route as PagesUUsernameHistoryRouteImport } from './routes/_pages/u/$username/history'
import { Route as PagesUUsernameFavoritesRouteImport } from './routes/_pages/u/$username/favorites'
import { Route as PagesPeopleSlugNovelRouteImport } from './routes/_pages/people/$slug/novel'
import { Route as PagesPeopleSlugMangaRouteImport } from './routes/_pages/people/$slug/manga'
import { Route as PagesPeopleSlugCharactersRouteImport } from './routes/_pages/people/$slug/characters'
import { Route as PagesPeopleSlugAnimeRouteImport } from './routes/_pages/people/$slug/anime'
import { Route as PagesNovelSlugStaffRouteImport } from './routes/_pages/novel/$slug/staff'
import { Route as PagesNovelSlugFranchiseRouteImport } from './routes/_pages/novel/$slug/franchise'
import { Route as PagesNovelSlugCharactersRouteImport } from './routes/_pages/novel/$slug/characters'
import { Route as PagesMangaSlugStaffRouteImport } from './routes/_pages/manga/$slug/staff'
import { Route as PagesMangaSlugFranchiseRouteImport } from './routes/_pages/manga/$slug/franchise'
import { Route as PagesMangaSlugCharactersRouteImport } from './routes/_pages/manga/$slug/characters'
import { Route as PagesEditEditIdUpdateRouteImport } from './routes/_pages/edit/$editId/update'
import { Route as PagesCollectionsReferenceUpdateRouteImport } from './routes/_pages/collections/$reference/update'
import { Route as PagesCharactersSlugVoicesRouteImport } from './routes/_pages/characters/$slug/voices'
import { Route as PagesCharactersSlugNovelRouteImport } from './routes/_pages/characters/$slug/novel'
import { Route as PagesCharactersSlugMangaRouteImport } from './routes/_pages/characters/$slug/manga'
import { Route as PagesCharactersSlugAnimeRouteImport } from './routes/_pages/characters/$slug/anime'
import { Route as PagesArticlesSlugUpdateRouteImport } from './routes/_pages/articles/$slug/update'
import { Route as PagesAnimeSlugStaffRouteImport } from './routes/_pages/anime/$slug/staff'
import { Route as PagesAnimeSlugMediaRouteImport } from './routes/_pages/anime/$slug/media'
import { Route as PagesAnimeSlugFranchiseRouteImport } from './routes/_pages/anime/$slug/franchise'
import { Route as PagesAnimeSlugCharactersRouteImport } from './routes/_pages/anime/$slug/characters'
import { Route as PagesAuthResetTokenRouteImport } from './routes/_pages/_auth/reset_.$token'
import { Route as PagesUUsernameListIndexRouteImport } from './routes/_pages/u/$username/list/index'
import { Route as PagesCommentsContent_typeSlugIndexRouteImport } from './routes/_pages/comments/$content_type/$slug/index'
import { Route as PagesUUsernameListContent_typeRouteImport } from './routes/_pages/u/$username/list/$content_type'
import { Route as PagesCommentsContent_typeSlugSplatRouteImport } from './routes/_pages/comments/$content_type/$slug/$'

const PagesRoute = PagesRouteImport.update({
  id: '/_pages',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesIndexRoute = PagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PagesRoute,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleRoute = AuthGoogleRouteImport.update({
  id: '/auth/google',
  path: '/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesSettingsRoute = PagesSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PagesRoute,
} as any)
const PagesScheduleRoute = PagesScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => PagesRoute,
} as any)
const PagesOauthRoute = PagesOauthRouteImport.update({
  id: '/oauth',
  path: '/oauth',
  getParentRoute: () => PagesRoute,
} as any)
const PagesAuthRoute = PagesAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => PagesRoute,
} as any)
const ApiSitemapIndexRoute = ApiSitemapIndexRouteImport.update({
  id: '/api/sitemap/',
  path: '/api/sitemap/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesSettingsIndexRoute = PagesSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PagesSettingsRoute,
} as any)
const PagesPeopleIndexRoute = PagesPeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => PagesRoute,
} as any)
const PagesNovelIndexRoute = PagesNovelIndexRouteImport.update({
  id: '/novel/',
  path: '/novel/',
  getParentRoute: () => PagesRoute,
} as any)
const PagesMangaIndexRoute = PagesMangaIndexRouteImport.update({
  id: '/manga/',
  path: '/manga/',
  getParentRoute: () => PagesRoute,
} as any)
const PagesEditIndexRoute = PagesEditIndexRouteImport.update({
  id: '/edit/',
  path: '/edit/',
  getParentRoute: () => PagesRoute,
} as any)
const PagesCollectionsIndexRoute = PagesCollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => PagesRoute,
} as any)
const PagesCharactersIndexRoute = PagesCharactersIndexRouteImport.update({
  id: '/characters/',
  path: '/characters/',
  getParentRoute: () => PagesRoute,
} as any)
const PagesArticlesIndexRoute = PagesArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => PagesRoute,
} as any)
const PagesAnimeIndexRoute = PagesAnimeIndexRouteImport.update({
  id: '/anime/',
  path: '/anime/',
  getParentRoute: () => PagesRoute,
} as any)
const AuthResetTokenRoute = AuthResetTokenRouteImport.update({
  id: '/auth/reset/$token',
  path: '/auth/reset/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthActivateTokenRoute = AuthActivateTokenRouteImport.update({
  id: '/auth/activate/$token',
  path: '/auth/activate/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSitemapNovelRoute = ApiSitemapNovelRouteImport.update({
  id: '/api/sitemap/novel',
  path: '/api/sitemap/novel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSitemapMangaRoute = ApiSitemapMangaRouteImport.update({
  id: '/api/sitemap/manga',
  path: '/api/sitemap/manga',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSitemapAnimeRoute = ApiSitemapAnimeRouteImport.update({
  id: '/api/sitemap/anime',
  path: '/api/sitemap/anime',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgNovelRoute = ApiOgNovelRouteImport.update({
  id: '/api/og/novel',
  path: '/api/og/novel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgMangaRoute = ApiOgMangaRouteImport.update({
  id: '/api/og/manga',
  path: '/api/og/manga',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgAnimeRoute = ApiOgAnimeRouteImport.update({
  id: '/api/og/anime',
  path: '/api/og/anime',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesUUsernameRoute = PagesUUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => PagesRoute,
} as any)
const PagesSettingsSecurityRoute = PagesSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => PagesSettingsRoute,
} as any)
const PagesSettingsProfileRoute = PagesSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PagesSettingsRoute,
} as any)
const PagesSettingsNotificationsRoute =
  PagesSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => PagesSettingsRoute,
  } as any)
const PagesSettingsListRoute = PagesSettingsListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => PagesSettingsRoute,
} as any)
const PagesSettingsCustomizationRoute =
  PagesSettingsCustomizationRouteImport.update({
    id: '/customization',
    path: '/customization',
    getParentRoute: () => PagesSettingsRoute,
  } as any)
const PagesSettingsApplicationsRoute =
  PagesSettingsApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => PagesSettingsRoute,
  } as any)
const PagesPeopleSlugRoute = PagesPeopleSlugRouteImport.update({
  id: '/people/$slug',
  path: '/people/$slug',
  getParentRoute: () => PagesRoute,
} as any)
const PagesNovelSlugRoute = PagesNovelSlugRouteImport.update({
  id: '/novel/$slug',
  path: '/novel/$slug',
  getParentRoute: () => PagesRoute,
} as any)
const PagesMangaSlugRoute = PagesMangaSlugRouteImport.update({
  id: '/manga/$slug',
  path: '/manga/$slug',
  getParentRoute: () => PagesRoute,
} as any)
const PagesEditNewRoute = PagesEditNewRouteImport.update({
  id: '/edit/new',
  path: '/edit/new',
  getParentRoute: () => PagesRoute,
} as any)
const PagesEditContentRoute = PagesEditContentRouteImport.update({
  id: '/edit/content',
  path: '/edit/content',
  getParentRoute: () => PagesRoute,
} as any)
const PagesEditEditIdRoute = PagesEditEditIdRouteImport.update({
  id: '/edit/$editId',
  path: '/edit/$editId',
  getParentRoute: () => PagesRoute,
} as any)
const PagesCommentsLatestRoute = PagesCommentsLatestRouteImport.update({
  id: '/comments/latest',
  path: '/comments/latest',
  getParentRoute: () => PagesRoute,
} as any)
const PagesCollectionsNewRoute = PagesCollectionsNewRouteImport.update({
  id: '/collections/new',
  path: '/collections/new',
  getParentRoute: () => PagesRoute,
} as any)
const PagesCollectionsReferenceRoute =
  PagesCollectionsReferenceRouteImport.update({
    id: '/collections/$reference',
    path: '/collections/$reference',
    getParentRoute: () => PagesRoute,
  } as any)
const PagesCharactersSlugRoute = PagesCharactersSlugRouteImport.update({
  id: '/characters/$slug',
  path: '/characters/$slug',
  getParentRoute: () => PagesRoute,
} as any)
const PagesArticlesNewRoute = PagesArticlesNewRouteImport.update({
  id: '/articles/new',
  path: '/articles/new',
  getParentRoute: () => PagesRoute,
} as any)
const PagesArticlesSlugRoute = PagesArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => PagesRoute,
} as any)
const PagesAnimeSlugRoute = PagesAnimeSlugRouteImport.update({
  id: '/anime/$slug',
  path: '/anime/$slug',
  getParentRoute: () => PagesRoute,
} as any)
const PagesAuthSignupRoute = PagesAuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => PagesAuthRoute,
} as any)
const PagesAuthResetRoute = PagesAuthResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => PagesAuthRoute,
} as any)
const PagesAuthLoginRoute = PagesAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PagesAuthRoute,
} as any)
const PagesUUsernameIndexRoute = PagesUUsernameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PagesUUsernameRoute,
} as any)
const PagesPeopleSlugIndexRoute = PagesPeopleSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PagesPeopleSlugRoute,
} as any)
const PagesNovelSlugIndexRoute = PagesNovelSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PagesNovelSlugRoute,
} as any)
const PagesMangaSlugIndexRoute = PagesMangaSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PagesMangaSlugRoute,
} as any)
const PagesEditEditIdIndexRoute = PagesEditEditIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PagesEditEditIdRoute,
} as any)
const PagesCollectionsReferenceIndexRoute =
  PagesCollectionsReferenceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PagesCollectionsReferenceRoute,
  } as any)
const PagesCharactersSlugIndexRoute =
  PagesCharactersSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PagesCharactersSlugRoute,
  } as any)
const PagesArticlesSlugIndexRoute = PagesArticlesSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PagesArticlesSlugRoute,
} as any)
const PagesAnimeSlugIndexRoute = PagesAnimeSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PagesAnimeSlugRoute,
} as any)
const PagesUUsernameListRoute = PagesUUsernameListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => PagesUUsernameRoute,
} as any)
const PagesUUsernameHistoryRoute = PagesUUsernameHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => PagesUUsernameRoute,
} as any)
const PagesUUsernameFavoritesRoute = PagesUUsernameFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => PagesUUsernameRoute,
} as any)
const PagesPeopleSlugNovelRoute = PagesPeopleSlugNovelRouteImport.update({
  id: '/novel',
  path: '/novel',
  getParentRoute: () => PagesPeopleSlugRoute,
} as any)
const PagesPeopleSlugMangaRoute = PagesPeopleSlugMangaRouteImport.update({
  id: '/manga',
  path: '/manga',
  getParentRoute: () => PagesPeopleSlugRoute,
} as any)
const PagesPeopleSlugCharactersRoute =
  PagesPeopleSlugCharactersRouteImport.update({
    id: '/characters',
    path: '/characters',
    getParentRoute: () => PagesPeopleSlugRoute,
  } as any)
const PagesPeopleSlugAnimeRoute = PagesPeopleSlugAnimeRouteImport.update({
  id: '/anime',
  path: '/anime',
  getParentRoute: () => PagesPeopleSlugRoute,
} as any)
const PagesNovelSlugStaffRoute = PagesNovelSlugStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => PagesNovelSlugRoute,
} as any)
const PagesNovelSlugFranchiseRoute = PagesNovelSlugFranchiseRouteImport.update({
  id: '/franchise',
  path: '/franchise',
  getParentRoute: () => PagesNovelSlugRoute,
} as any)
const PagesNovelSlugCharactersRoute =
  PagesNovelSlugCharactersRouteImport.update({
    id: '/characters',
    path: '/characters',
    getParentRoute: () => PagesNovelSlugRoute,
  } as any)
const PagesMangaSlugStaffRoute = PagesMangaSlugStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => PagesMangaSlugRoute,
} as any)
const PagesMangaSlugFranchiseRoute = PagesMangaSlugFranchiseRouteImport.update({
  id: '/franchise',
  path: '/franchise',
  getParentRoute: () => PagesMangaSlugRoute,
} as any)
const PagesMangaSlugCharactersRoute =
  PagesMangaSlugCharactersRouteImport.update({
    id: '/characters',
    path: '/characters',
    getParentRoute: () => PagesMangaSlugRoute,
  } as any)
const PagesEditEditIdUpdateRoute = PagesEditEditIdUpdateRouteImport.update({
  id: '/update',
  path: '/update',
  getParentRoute: () => PagesEditEditIdRoute,
} as any)
const PagesCollectionsReferenceUpdateRoute =
  PagesCollectionsReferenceUpdateRouteImport.update({
    id: '/update',
    path: '/update',
    getParentRoute: () => PagesCollectionsReferenceRoute,
  } as any)
const PagesCharactersSlugVoicesRoute =
  PagesCharactersSlugVoicesRouteImport.update({
    id: '/voices',
    path: '/voices',
    getParentRoute: () => PagesCharactersSlugRoute,
  } as any)
const PagesCharactersSlugNovelRoute =
  PagesCharactersSlugNovelRouteImport.update({
    id: '/novel',
    path: '/novel',
    getParentRoute: () => PagesCharactersSlugRoute,
  } as any)
const PagesCharactersSlugMangaRoute =
  PagesCharactersSlugMangaRouteImport.update({
    id: '/manga',
    path: '/manga',
    getParentRoute: () => PagesCharactersSlugRoute,
  } as any)
const PagesCharactersSlugAnimeRoute =
  PagesCharactersSlugAnimeRouteImport.update({
    id: '/anime',
    path: '/anime',
    getParentRoute: () => PagesCharactersSlugRoute,
  } as any)
const PagesArticlesSlugUpdateRoute = PagesArticlesSlugUpdateRouteImport.update({
  id: '/update',
  path: '/update',
  getParentRoute: () => PagesArticlesSlugRoute,
} as any)
const PagesAnimeSlugStaffRoute = PagesAnimeSlugStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => PagesAnimeSlugRoute,
} as any)
const PagesAnimeSlugMediaRoute = PagesAnimeSlugMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => PagesAnimeSlugRoute,
} as any)
const PagesAnimeSlugFranchiseRoute = PagesAnimeSlugFranchiseRouteImport.update({
  id: '/franchise',
  path: '/franchise',
  getParentRoute: () => PagesAnimeSlugRoute,
} as any)
const PagesAnimeSlugCharactersRoute =
  PagesAnimeSlugCharactersRouteImport.update({
    id: '/characters',
    path: '/characters',
    getParentRoute: () => PagesAnimeSlugRoute,
  } as any)
const PagesAuthResetTokenRoute = PagesAuthResetTokenRouteImport.update({
  id: '/reset_/$token',
  path: '/reset/$token',
  getParentRoute: () => PagesAuthRoute,
} as any)
const PagesUUsernameListIndexRoute = PagesUUsernameListIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PagesUUsernameListRoute,
} as any)
const PagesCommentsContent_typeSlugIndexRoute =
  PagesCommentsContent_typeSlugIndexRouteImport.update({
    id: '/comments/$content_type/$slug/',
    path: '/comments/$content_type/$slug/',
    getParentRoute: () => PagesRoute,
  } as any)
const PagesUUsernameListContent_typeRoute =
  PagesUUsernameListContent_typeRouteImport.update({
    id: '/$content_type',
    path: '/$content_type',
    getParentRoute: () => PagesUUsernameListRoute,
  } as any)
const PagesCommentsContent_typeSlugSplatRoute =
  PagesCommentsContent_typeSlugSplatRouteImport.update({
    id: '/comments/$content_type/$slug/$',
    path: '/comments/$content_type/$slug/$',
    getParentRoute: () => PagesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PagesIndexRoute
  '/oauth': typeof PagesOauthRoute
  '/schedule': typeof PagesScheduleRoute
  '/settings': typeof PagesSettingsRouteWithChildren
  '/auth/google': typeof AuthGoogleRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/login': typeof PagesAuthLoginRoute
  '/reset': typeof PagesAuthResetRoute
  '/signup': typeof PagesAuthSignupRoute
  '/anime/$slug': typeof PagesAnimeSlugRouteWithChildren
  '/articles/$slug': typeof PagesArticlesSlugRouteWithChildren
  '/articles/new': typeof PagesArticlesNewRoute
  '/characters/$slug': typeof PagesCharactersSlugRouteWithChildren
  '/collections/$reference': typeof PagesCollectionsReferenceRouteWithChildren
  '/collections/new': typeof PagesCollectionsNewRoute
  '/comments/latest': typeof PagesCommentsLatestRoute
  '/edit/$editId': typeof PagesEditEditIdRouteWithChildren
  '/edit/content': typeof PagesEditContentRoute
  '/edit/new': typeof PagesEditNewRoute
  '/manga/$slug': typeof PagesMangaSlugRouteWithChildren
  '/novel/$slug': typeof PagesNovelSlugRouteWithChildren
  '/people/$slug': typeof PagesPeopleSlugRouteWithChildren
  '/settings/applications': typeof PagesSettingsApplicationsRoute
  '/settings/customization': typeof PagesSettingsCustomizationRoute
  '/settings/list': typeof PagesSettingsListRoute
  '/settings/notifications': typeof PagesSettingsNotificationsRoute
  '/settings/profile': typeof PagesSettingsProfileRoute
  '/settings/security': typeof PagesSettingsSecurityRoute
  '/u/$username': typeof PagesUUsernameRouteWithChildren
  '/api/og/anime': typeof ApiOgAnimeRoute
  '/api/og/manga': typeof ApiOgMangaRoute
  '/api/og/novel': typeof ApiOgNovelRoute
  '/api/sitemap/anime': typeof ApiSitemapAnimeRoute
  '/api/sitemap/manga': typeof ApiSitemapMangaRoute
  '/api/sitemap/novel': typeof ApiSitemapNovelRoute
  '/auth/activate/$token': typeof AuthActivateTokenRoute
  '/auth/reset/$token': typeof AuthResetTokenRoute
  '/anime/': typeof PagesAnimeIndexRoute
  '/articles/': typeof PagesArticlesIndexRoute
  '/characters/': typeof PagesCharactersIndexRoute
  '/collections/': typeof PagesCollectionsIndexRoute
  '/edit/': typeof PagesEditIndexRoute
  '/manga/': typeof PagesMangaIndexRoute
  '/novel/': typeof PagesNovelIndexRoute
  '/people/': typeof PagesPeopleIndexRoute
  '/settings/': typeof PagesSettingsIndexRoute
  '/api/sitemap/': typeof ApiSitemapIndexRoute
  '/reset/$token': typeof PagesAuthResetTokenRoute
  '/anime/$slug/characters': typeof PagesAnimeSlugCharactersRoute
  '/anime/$slug/franchise': typeof PagesAnimeSlugFranchiseRoute
  '/anime/$slug/media': typeof PagesAnimeSlugMediaRoute
  '/anime/$slug/staff': typeof PagesAnimeSlugStaffRoute
  '/articles/$slug/update': typeof PagesArticlesSlugUpdateRoute
  '/characters/$slug/anime': typeof PagesCharactersSlugAnimeRoute
  '/characters/$slug/manga': typeof PagesCharactersSlugMangaRoute
  '/characters/$slug/novel': typeof PagesCharactersSlugNovelRoute
  '/characters/$slug/voices': typeof PagesCharactersSlugVoicesRoute
  '/collections/$reference/update': typeof PagesCollectionsReferenceUpdateRoute
  '/edit/$editId/update': typeof PagesEditEditIdUpdateRoute
  '/manga/$slug/characters': typeof PagesMangaSlugCharactersRoute
  '/manga/$slug/franchise': typeof PagesMangaSlugFranchiseRoute
  '/manga/$slug/staff': typeof PagesMangaSlugStaffRoute
  '/novel/$slug/characters': typeof PagesNovelSlugCharactersRoute
  '/novel/$slug/franchise': typeof PagesNovelSlugFranchiseRoute
  '/novel/$slug/staff': typeof PagesNovelSlugStaffRoute
  '/people/$slug/anime': typeof PagesPeopleSlugAnimeRoute
  '/people/$slug/characters': typeof PagesPeopleSlugCharactersRoute
  '/people/$slug/manga': typeof PagesPeopleSlugMangaRoute
  '/people/$slug/novel': typeof PagesPeopleSlugNovelRoute
  '/u/$username/favorites': typeof PagesUUsernameFavoritesRoute
  '/u/$username/history': typeof PagesUUsernameHistoryRoute
  '/u/$username/list': typeof PagesUUsernameListRouteWithChildren
  '/anime/$slug/': typeof PagesAnimeSlugIndexRoute
  '/articles/$slug/': typeof PagesArticlesSlugIndexRoute
  '/characters/$slug/': typeof PagesCharactersSlugIndexRoute
  '/collections/$reference/': typeof PagesCollectionsReferenceIndexRoute
  '/edit/$editId/': typeof PagesEditEditIdIndexRoute
  '/manga/$slug/': typeof PagesMangaSlugIndexRoute
  '/novel/$slug/': typeof PagesNovelSlugIndexRoute
  '/people/$slug/': typeof PagesPeopleSlugIndexRoute
  '/u/$username/': typeof PagesUUsernameIndexRoute
  '/comments/$content_type/$slug/$': typeof PagesCommentsContent_typeSlugSplatRoute
  '/u/$username/list/$content_type': typeof PagesUUsernameListContent_typeRoute
  '/comments/$content_type/$slug/': typeof PagesCommentsContent_typeSlugIndexRoute
  '/u/$username/list/': typeof PagesUUsernameListIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PagesIndexRoute
  '/oauth': typeof PagesOauthRoute
  '/schedule': typeof PagesScheduleRoute
  '/auth/google': typeof AuthGoogleRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/login': typeof PagesAuthLoginRoute
  '/reset': typeof PagesAuthResetRoute
  '/signup': typeof PagesAuthSignupRoute
  '/articles/new': typeof PagesArticlesNewRoute
  '/collections/new': typeof PagesCollectionsNewRoute
  '/comments/latest': typeof PagesCommentsLatestRoute
  '/edit/content': typeof PagesEditContentRoute
  '/edit/new': typeof PagesEditNewRoute
  '/settings/applications': typeof PagesSettingsApplicationsRoute
  '/settings/customization': typeof PagesSettingsCustomizationRoute
  '/settings/list': typeof PagesSettingsListRoute
  '/settings/notifications': typeof PagesSettingsNotificationsRoute
  '/settings/profile': typeof PagesSettingsProfileRoute
  '/settings/security': typeof PagesSettingsSecurityRoute
  '/api/og/anime': typeof ApiOgAnimeRoute
  '/api/og/manga': typeof ApiOgMangaRoute
  '/api/og/novel': typeof ApiOgNovelRoute
  '/api/sitemap/anime': typeof ApiSitemapAnimeRoute
  '/api/sitemap/manga': typeof ApiSitemapMangaRoute
  '/api/sitemap/novel': typeof ApiSitemapNovelRoute
  '/auth/activate/$token': typeof AuthActivateTokenRoute
  '/auth/reset/$token': typeof AuthResetTokenRoute
  '/anime': typeof PagesAnimeIndexRoute
  '/articles': typeof PagesArticlesIndexRoute
  '/characters': typeof PagesCharactersIndexRoute
  '/collections': typeof PagesCollectionsIndexRoute
  '/edit': typeof PagesEditIndexRoute
  '/manga': typeof PagesMangaIndexRoute
  '/novel': typeof PagesNovelIndexRoute
  '/people': typeof PagesPeopleIndexRoute
  '/settings': typeof PagesSettingsIndexRoute
  '/api/sitemap': typeof ApiSitemapIndexRoute
  '/reset/$token': typeof PagesAuthResetTokenRoute
  '/anime/$slug/characters': typeof PagesAnimeSlugCharactersRoute
  '/anime/$slug/franchise': typeof PagesAnimeSlugFranchiseRoute
  '/anime/$slug/media': typeof PagesAnimeSlugMediaRoute
  '/anime/$slug/staff': typeof PagesAnimeSlugStaffRoute
  '/articles/$slug/update': typeof PagesArticlesSlugUpdateRoute
  '/characters/$slug/anime': typeof PagesCharactersSlugAnimeRoute
  '/characters/$slug/manga': typeof PagesCharactersSlugMangaRoute
  '/characters/$slug/novel': typeof PagesCharactersSlugNovelRoute
  '/characters/$slug/voices': typeof PagesCharactersSlugVoicesRoute
  '/collections/$reference/update': typeof PagesCollectionsReferenceUpdateRoute
  '/edit/$editId/update': typeof PagesEditEditIdUpdateRoute
  '/manga/$slug/characters': typeof PagesMangaSlugCharactersRoute
  '/manga/$slug/franchise': typeof PagesMangaSlugFranchiseRoute
  '/manga/$slug/staff': typeof PagesMangaSlugStaffRoute
  '/novel/$slug/characters': typeof PagesNovelSlugCharactersRoute
  '/novel/$slug/franchise': typeof PagesNovelSlugFranchiseRoute
  '/novel/$slug/staff': typeof PagesNovelSlugStaffRoute
  '/people/$slug/anime': typeof PagesPeopleSlugAnimeRoute
  '/people/$slug/characters': typeof PagesPeopleSlugCharactersRoute
  '/people/$slug/manga': typeof PagesPeopleSlugMangaRoute
  '/people/$slug/novel': typeof PagesPeopleSlugNovelRoute
  '/u/$username/favorites': typeof PagesUUsernameFavoritesRoute
  '/u/$username/history': typeof PagesUUsernameHistoryRoute
  '/anime/$slug': typeof PagesAnimeSlugIndexRoute
  '/articles/$slug': typeof PagesArticlesSlugIndexRoute
  '/characters/$slug': typeof PagesCharactersSlugIndexRoute
  '/collections/$reference': typeof PagesCollectionsReferenceIndexRoute
  '/edit/$editId': typeof PagesEditEditIdIndexRoute
  '/manga/$slug': typeof PagesMangaSlugIndexRoute
  '/novel/$slug': typeof PagesNovelSlugIndexRoute
  '/people/$slug': typeof PagesPeopleSlugIndexRoute
  '/u/$username': typeof PagesUUsernameIndexRoute
  '/comments/$content_type/$slug/$': typeof PagesCommentsContent_typeSlugSplatRoute
  '/u/$username/list/$content_type': typeof PagesUUsernameListContent_typeRoute
  '/comments/$content_type/$slug': typeof PagesCommentsContent_typeSlugIndexRoute
  '/u/$username/list': typeof PagesUUsernameListIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_pages': typeof PagesRouteWithChildren
  '/_pages/_auth': typeof PagesAuthRouteWithChildren
  '/_pages/oauth': typeof PagesOauthRoute
  '/_pages/schedule': typeof PagesScheduleRoute
  '/_pages/settings': typeof PagesSettingsRouteWithChildren
  '/auth/google': typeof AuthGoogleRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/_pages/': typeof PagesIndexRoute
  '/_pages/_auth/login': typeof PagesAuthLoginRoute
  '/_pages/_auth/reset': typeof PagesAuthResetRoute
  '/_pages/_auth/signup': typeof PagesAuthSignupRoute
  '/_pages/anime/$slug': typeof PagesAnimeSlugRouteWithChildren
  '/_pages/articles/$slug': typeof PagesArticlesSlugRouteWithChildren
  '/_pages/articles/new': typeof PagesArticlesNewRoute
  '/_pages/characters/$slug': typeof PagesCharactersSlugRouteWithChildren
  '/_pages/collections/$reference': typeof PagesCollectionsReferenceRouteWithChildren
  '/_pages/collections/new': typeof PagesCollectionsNewRoute
  '/_pages/comments/latest': typeof PagesCommentsLatestRoute
  '/_pages/edit/$editId': typeof PagesEditEditIdRouteWithChildren
  '/_pages/edit/content': typeof PagesEditContentRoute
  '/_pages/edit/new': typeof PagesEditNewRoute
  '/_pages/manga/$slug': typeof PagesMangaSlugRouteWithChildren
  '/_pages/novel/$slug': typeof PagesNovelSlugRouteWithChildren
  '/_pages/people/$slug': typeof PagesPeopleSlugRouteWithChildren
  '/_pages/settings/applications': typeof PagesSettingsApplicationsRoute
  '/_pages/settings/customization': typeof PagesSettingsCustomizationRoute
  '/_pages/settings/list': typeof PagesSettingsListRoute
  '/_pages/settings/notifications': typeof PagesSettingsNotificationsRoute
  '/_pages/settings/profile': typeof PagesSettingsProfileRoute
  '/_pages/settings/security': typeof PagesSettingsSecurityRoute
  '/_pages/u/$username': typeof PagesUUsernameRouteWithChildren
  '/api/og/anime': typeof ApiOgAnimeRoute
  '/api/og/manga': typeof ApiOgMangaRoute
  '/api/og/novel': typeof ApiOgNovelRoute
  '/api/sitemap/anime': typeof ApiSitemapAnimeRoute
  '/api/sitemap/manga': typeof ApiSitemapMangaRoute
  '/api/sitemap/novel': typeof ApiSitemapNovelRoute
  '/auth/activate/$token': typeof AuthActivateTokenRoute
  '/auth/reset/$token': typeof AuthResetTokenRoute
  '/_pages/anime/': typeof PagesAnimeIndexRoute
  '/_pages/articles/': typeof PagesArticlesIndexRoute
  '/_pages/characters/': typeof PagesCharactersIndexRoute
  '/_pages/collections/': typeof PagesCollectionsIndexRoute
  '/_pages/edit/': typeof PagesEditIndexRoute
  '/_pages/manga/': typeof PagesMangaIndexRoute
  '/_pages/novel/': typeof PagesNovelIndexRoute
  '/_pages/people/': typeof PagesPeopleIndexRoute
  '/_pages/settings/': typeof PagesSettingsIndexRoute
  '/api/sitemap/': typeof ApiSitemapIndexRoute
  '/_pages/_auth/reset_/$token': typeof PagesAuthResetTokenRoute
  '/_pages/anime/$slug/characters': typeof PagesAnimeSlugCharactersRoute
  '/_pages/anime/$slug/franchise': typeof PagesAnimeSlugFranchiseRoute
  '/_pages/anime/$slug/media': typeof PagesAnimeSlugMediaRoute
  '/_pages/anime/$slug/staff': typeof PagesAnimeSlugStaffRoute
  '/_pages/articles/$slug/update': typeof PagesArticlesSlugUpdateRoute
  '/_pages/characters/$slug/anime': typeof PagesCharactersSlugAnimeRoute
  '/_pages/characters/$slug/manga': typeof PagesCharactersSlugMangaRoute
  '/_pages/characters/$slug/novel': typeof PagesCharactersSlugNovelRoute
  '/_pages/characters/$slug/voices': typeof PagesCharactersSlugVoicesRoute
  '/_pages/collections/$reference/update': typeof PagesCollectionsReferenceUpdateRoute
  '/_pages/edit/$editId/update': typeof PagesEditEditIdUpdateRoute
  '/_pages/manga/$slug/characters': typeof PagesMangaSlugCharactersRoute
  '/_pages/manga/$slug/franchise': typeof PagesMangaSlugFranchiseRoute
  '/_pages/manga/$slug/staff': typeof PagesMangaSlugStaffRoute
  '/_pages/novel/$slug/characters': typeof PagesNovelSlugCharactersRoute
  '/_pages/novel/$slug/franchise': typeof PagesNovelSlugFranchiseRoute
  '/_pages/novel/$slug/staff': typeof PagesNovelSlugStaffRoute
  '/_pages/people/$slug/anime': typeof PagesPeopleSlugAnimeRoute
  '/_pages/people/$slug/characters': typeof PagesPeopleSlugCharactersRoute
  '/_pages/people/$slug/manga': typeof PagesPeopleSlugMangaRoute
  '/_pages/people/$slug/novel': typeof PagesPeopleSlugNovelRoute
  '/_pages/u/$username/favorites': typeof PagesUUsernameFavoritesRoute
  '/_pages/u/$username/history': typeof PagesUUsernameHistoryRoute
  '/_pages/u/$username/list': typeof PagesUUsernameListRouteWithChildren
  '/_pages/anime/$slug/': typeof PagesAnimeSlugIndexRoute
  '/_pages/articles/$slug/': typeof PagesArticlesSlugIndexRoute
  '/_pages/characters/$slug/': typeof PagesCharactersSlugIndexRoute
  '/_pages/collections/$reference/': typeof PagesCollectionsReferenceIndexRoute
  '/_pages/edit/$editId/': typeof PagesEditEditIdIndexRoute
  '/_pages/manga/$slug/': typeof PagesMangaSlugIndexRoute
  '/_pages/novel/$slug/': typeof PagesNovelSlugIndexRoute
  '/_pages/people/$slug/': typeof PagesPeopleSlugIndexRoute
  '/_pages/u/$username/': typeof PagesUUsernameIndexRoute
  '/_pages/comments/$content_type/$slug/$': typeof PagesCommentsContent_typeSlugSplatRoute
  '/_pages/u/$username/list/$content_type': typeof PagesUUsernameListContent_typeRoute
  '/_pages/comments/$content_type/$slug/': typeof PagesCommentsContent_typeSlugIndexRoute
  '/_pages/u/$username/list/': typeof PagesUUsernameListIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/oauth'
    | '/schedule'
    | '/settings'
    | '/auth/google'
    | '/auth/logout'
    | '/login'
    | '/reset'
    | '/signup'
    | '/anime/$slug'
    | '/articles/$slug'
    | '/articles/new'
    | '/characters/$slug'
    | '/collections/$reference'
    | '/collections/new'
    | '/comments/latest'
    | '/edit/$editId'
    | '/edit/content'
    | '/edit/new'
    | '/manga/$slug'
    | '/novel/$slug'
    | '/people/$slug'
    | '/settings/applications'
    | '/settings/customization'
    | '/settings/list'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/security'
    | '/u/$username'
    | '/api/og/anime'
    | '/api/og/manga'
    | '/api/og/novel'
    | '/api/sitemap/anime'
    | '/api/sitemap/manga'
    | '/api/sitemap/novel'
    | '/auth/activate/$token'
    | '/auth/reset/$token'
    | '/anime/'
    | '/articles/'
    | '/characters/'
    | '/collections/'
    | '/edit/'
    | '/manga/'
    | '/novel/'
    | '/people/'
    | '/settings/'
    | '/api/sitemap/'
    | '/reset/$token'
    | '/anime/$slug/characters'
    | '/anime/$slug/franchise'
    | '/anime/$slug/media'
    | '/anime/$slug/staff'
    | '/articles/$slug/update'
    | '/characters/$slug/anime'
    | '/characters/$slug/manga'
    | '/characters/$slug/novel'
    | '/characters/$slug/voices'
    | '/collections/$reference/update'
    | '/edit/$editId/update'
    | '/manga/$slug/characters'
    | '/manga/$slug/franchise'
    | '/manga/$slug/staff'
    | '/novel/$slug/characters'
    | '/novel/$slug/franchise'
    | '/novel/$slug/staff'
    | '/people/$slug/anime'
    | '/people/$slug/characters'
    | '/people/$slug/manga'
    | '/people/$slug/novel'
    | '/u/$username/favorites'
    | '/u/$username/history'
    | '/u/$username/list'
    | '/anime/$slug/'
    | '/articles/$slug/'
    | '/characters/$slug/'
    | '/collections/$reference/'
    | '/edit/$editId/'
    | '/manga/$slug/'
    | '/novel/$slug/'
    | '/people/$slug/'
    | '/u/$username/'
    | '/comments/$content_type/$slug/$'
    | '/u/$username/list/$content_type'
    | '/comments/$content_type/$slug/'
    | '/u/$username/list/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/oauth'
    | '/schedule'
    | '/auth/google'
    | '/auth/logout'
    | '/login'
    | '/reset'
    | '/signup'
    | '/articles/new'
    | '/collections/new'
    | '/comments/latest'
    | '/edit/content'
    | '/edit/new'
    | '/settings/applications'
    | '/settings/customization'
    | '/settings/list'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/security'
    | '/api/og/anime'
    | '/api/og/manga'
    | '/api/og/novel'
    | '/api/sitemap/anime'
    | '/api/sitemap/manga'
    | '/api/sitemap/novel'
    | '/auth/activate/$token'
    | '/auth/reset/$token'
    | '/anime'
    | '/articles'
    | '/characters'
    | '/collections'
    | '/edit'
    | '/manga'
    | '/novel'
    | '/people'
    | '/settings'
    | '/api/sitemap'
    | '/reset/$token'
    | '/anime/$slug/characters'
    | '/anime/$slug/franchise'
    | '/anime/$slug/media'
    | '/anime/$slug/staff'
    | '/articles/$slug/update'
    | '/characters/$slug/anime'
    | '/characters/$slug/manga'
    | '/characters/$slug/novel'
    | '/characters/$slug/voices'
    | '/collections/$reference/update'
    | '/edit/$editId/update'
    | '/manga/$slug/characters'
    | '/manga/$slug/franchise'
    | '/manga/$slug/staff'
    | '/novel/$slug/characters'
    | '/novel/$slug/franchise'
    | '/novel/$slug/staff'
    | '/people/$slug/anime'
    | '/people/$slug/characters'
    | '/people/$slug/manga'
    | '/people/$slug/novel'
    | '/u/$username/favorites'
    | '/u/$username/history'
    | '/anime/$slug'
    | '/articles/$slug'
    | '/characters/$slug'
    | '/collections/$reference'
    | '/edit/$editId'
    | '/manga/$slug'
    | '/novel/$slug'
    | '/people/$slug'
    | '/u/$username'
    | '/comments/$content_type/$slug/$'
    | '/u/$username/list/$content_type'
    | '/comments/$content_type/$slug'
    | '/u/$username/list'
  id:
    | '__root__'
    | '/_pages'
    | '/_pages/_auth'
    | '/_pages/oauth'
    | '/_pages/schedule'
    | '/_pages/settings'
    | '/auth/google'
    | '/auth/logout'
    | '/_pages/'
    | '/_pages/_auth/login'
    | '/_pages/_auth/reset'
    | '/_pages/_auth/signup'
    | '/_pages/anime/$slug'
    | '/_pages/articles/$slug'
    | '/_pages/articles/new'
    | '/_pages/characters/$slug'
    | '/_pages/collections/$reference'
    | '/_pages/collections/new'
    | '/_pages/comments/latest'
    | '/_pages/edit/$editId'
    | '/_pages/edit/content'
    | '/_pages/edit/new'
    | '/_pages/manga/$slug'
    | '/_pages/novel/$slug'
    | '/_pages/people/$slug'
    | '/_pages/settings/applications'
    | '/_pages/settings/customization'
    | '/_pages/settings/list'
    | '/_pages/settings/notifications'
    | '/_pages/settings/profile'
    | '/_pages/settings/security'
    | '/_pages/u/$username'
    | '/api/og/anime'
    | '/api/og/manga'
    | '/api/og/novel'
    | '/api/sitemap/anime'
    | '/api/sitemap/manga'
    | '/api/sitemap/novel'
    | '/auth/activate/$token'
    | '/auth/reset/$token'
    | '/_pages/anime/'
    | '/_pages/articles/'
    | '/_pages/characters/'
    | '/_pages/collections/'
    | '/_pages/edit/'
    | '/_pages/manga/'
    | '/_pages/novel/'
    | '/_pages/people/'
    | '/_pages/settings/'
    | '/api/sitemap/'
    | '/_pages/_auth/reset_/$token'
    | '/_pages/anime/$slug/characters'
    | '/_pages/anime/$slug/franchise'
    | '/_pages/anime/$slug/media'
    | '/_pages/anime/$slug/staff'
    | '/_pages/articles/$slug/update'
    | '/_pages/characters/$slug/anime'
    | '/_pages/characters/$slug/manga'
    | '/_pages/characters/$slug/novel'
    | '/_pages/characters/$slug/voices'
    | '/_pages/collections/$reference/update'
    | '/_pages/edit/$editId/update'
    | '/_pages/manga/$slug/characters'
    | '/_pages/manga/$slug/franchise'
    | '/_pages/manga/$slug/staff'
    | '/_pages/novel/$slug/characters'
    | '/_pages/novel/$slug/franchise'
    | '/_pages/novel/$slug/staff'
    | '/_pages/people/$slug/anime'
    | '/_pages/people/$slug/characters'
    | '/_pages/people/$slug/manga'
    | '/_pages/people/$slug/novel'
    | '/_pages/u/$username/favorites'
    | '/_pages/u/$username/history'
    | '/_pages/u/$username/list'
    | '/_pages/anime/$slug/'
    | '/_pages/articles/$slug/'
    | '/_pages/characters/$slug/'
    | '/_pages/collections/$reference/'
    | '/_pages/edit/$editId/'
    | '/_pages/manga/$slug/'
    | '/_pages/novel/$slug/'
    | '/_pages/people/$slug/'
    | '/_pages/u/$username/'
    | '/_pages/comments/$content_type/$slug/$'
    | '/_pages/u/$username/list/$content_type'
    | '/_pages/comments/$content_type/$slug/'
    | '/_pages/u/$username/list/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PagesRoute: typeof PagesRouteWithChildren
  AuthGoogleRoute: typeof AuthGoogleRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  ApiOgAnimeRoute: typeof ApiOgAnimeRoute
  ApiOgMangaRoute: typeof ApiOgMangaRoute
  ApiOgNovelRoute: typeof ApiOgNovelRoute
  ApiSitemapAnimeRoute: typeof ApiSitemapAnimeRoute
  ApiSitemapMangaRoute: typeof ApiSitemapMangaRoute
  ApiSitemapNovelRoute: typeof ApiSitemapNovelRoute
  AuthActivateTokenRoute: typeof AuthActivateTokenRoute
  AuthResetTokenRoute: typeof AuthResetTokenRoute
  ApiSitemapIndexRoute: typeof ApiSitemapIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_pages': {
      id: '/_pages'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pages/': {
      id: '/_pages/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PagesIndexRouteImport
      parentRoute: typeof PagesRoute
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google': {
      id: '/auth/google'
      path: '/auth/google'
      fullPath: '/auth/google'
      preLoaderRoute: typeof AuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pages/settings': {
      id: '/_pages/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof PagesSettingsRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/schedule': {
      id: '/_pages/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof PagesScheduleRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/oauth': {
      id: '/_pages/oauth'
      path: '/oauth'
      fullPath: '/oauth'
      preLoaderRoute: typeof PagesOauthRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/_auth': {
      id: '/_pages/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PagesAuthRouteImport
      parentRoute: typeof PagesRoute
    }
    '/api/sitemap/': {
      id: '/api/sitemap/'
      path: '/api/sitemap'
      fullPath: '/api/sitemap/'
      preLoaderRoute: typeof ApiSitemapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pages/settings/': {
      id: '/_pages/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof PagesSettingsIndexRouteImport
      parentRoute: typeof PagesSettingsRoute
    }
    '/_pages/people/': {
      id: '/_pages/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof PagesPeopleIndexRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/novel/': {
      id: '/_pages/novel/'
      path: '/novel'
      fullPath: '/novel/'
      preLoaderRoute: typeof PagesNovelIndexRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/manga/': {
      id: '/_pages/manga/'
      path: '/manga'
      fullPath: '/manga/'
      preLoaderRoute: typeof PagesMangaIndexRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/edit/': {
      id: '/_pages/edit/'
      path: '/edit'
      fullPath: '/edit/'
      preLoaderRoute: typeof PagesEditIndexRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/collections/': {
      id: '/_pages/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof PagesCollectionsIndexRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/characters/': {
      id: '/_pages/characters/'
      path: '/characters'
      fullPath: '/characters/'
      preLoaderRoute: typeof PagesCharactersIndexRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/articles/': {
      id: '/_pages/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof PagesArticlesIndexRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/anime/': {
      id: '/_pages/anime/'
      path: '/anime'
      fullPath: '/anime/'
      preLoaderRoute: typeof PagesAnimeIndexRouteImport
      parentRoute: typeof PagesRoute
    }
    '/auth/reset/$token': {
      id: '/auth/reset/$token'
      path: '/auth/reset/$token'
      fullPath: '/auth/reset/$token'
      preLoaderRoute: typeof AuthResetTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/activate/$token': {
      id: '/auth/activate/$token'
      path: '/auth/activate/$token'
      fullPath: '/auth/activate/$token'
      preLoaderRoute: typeof AuthActivateTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sitemap/novel': {
      id: '/api/sitemap/novel'
      path: '/api/sitemap/novel'
      fullPath: '/api/sitemap/novel'
      preLoaderRoute: typeof ApiSitemapNovelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sitemap/manga': {
      id: '/api/sitemap/manga'
      path: '/api/sitemap/manga'
      fullPath: '/api/sitemap/manga'
      preLoaderRoute: typeof ApiSitemapMangaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sitemap/anime': {
      id: '/api/sitemap/anime'
      path: '/api/sitemap/anime'
      fullPath: '/api/sitemap/anime'
      preLoaderRoute: typeof ApiSitemapAnimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/novel': {
      id: '/api/og/novel'
      path: '/api/og/novel'
      fullPath: '/api/og/novel'
      preLoaderRoute: typeof ApiOgNovelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/manga': {
      id: '/api/og/manga'
      path: '/api/og/manga'
      fullPath: '/api/og/manga'
      preLoaderRoute: typeof ApiOgMangaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/anime': {
      id: '/api/og/anime'
      path: '/api/og/anime'
      fullPath: '/api/og/anime'
      preLoaderRoute: typeof ApiOgAnimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pages/u/$username': {
      id: '/_pages/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof PagesUUsernameRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/settings/security': {
      id: '/_pages/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof PagesSettingsSecurityRouteImport
      parentRoute: typeof PagesSettingsRoute
    }
    '/_pages/settings/profile': {
      id: '/_pages/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof PagesSettingsProfileRouteImport
      parentRoute: typeof PagesSettingsRoute
    }
    '/_pages/settings/notifications': {
      id: '/_pages/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof PagesSettingsNotificationsRouteImport
      parentRoute: typeof PagesSettingsRoute
    }
    '/_pages/settings/list': {
      id: '/_pages/settings/list'
      path: '/list'
      fullPath: '/settings/list'
      preLoaderRoute: typeof PagesSettingsListRouteImport
      parentRoute: typeof PagesSettingsRoute
    }
    '/_pages/settings/customization': {
      id: '/_pages/settings/customization'
      path: '/customization'
      fullPath: '/settings/customization'
      preLoaderRoute: typeof PagesSettingsCustomizationRouteImport
      parentRoute: typeof PagesSettingsRoute
    }
    '/_pages/settings/applications': {
      id: '/_pages/settings/applications'
      path: '/applications'
      fullPath: '/settings/applications'
      preLoaderRoute: typeof PagesSettingsApplicationsRouteImport
      parentRoute: typeof PagesSettingsRoute
    }
    '/_pages/people/$slug': {
      id: '/_pages/people/$slug'
      path: '/people/$slug'
      fullPath: '/people/$slug'
      preLoaderRoute: typeof PagesPeopleSlugRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/novel/$slug': {
      id: '/_pages/novel/$slug'
      path: '/novel/$slug'
      fullPath: '/novel/$slug'
      preLoaderRoute: typeof PagesNovelSlugRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/manga/$slug': {
      id: '/_pages/manga/$slug'
      path: '/manga/$slug'
      fullPath: '/manga/$slug'
      preLoaderRoute: typeof PagesMangaSlugRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/edit/new': {
      id: '/_pages/edit/new'
      path: '/edit/new'
      fullPath: '/edit/new'
      preLoaderRoute: typeof PagesEditNewRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/edit/content': {
      id: '/_pages/edit/content'
      path: '/edit/content'
      fullPath: '/edit/content'
      preLoaderRoute: typeof PagesEditContentRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/edit/$editId': {
      id: '/_pages/edit/$editId'
      path: '/edit/$editId'
      fullPath: '/edit/$editId'
      preLoaderRoute: typeof PagesEditEditIdRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/comments/latest': {
      id: '/_pages/comments/latest'
      path: '/comments/latest'
      fullPath: '/comments/latest'
      preLoaderRoute: typeof PagesCommentsLatestRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/collections/new': {
      id: '/_pages/collections/new'
      path: '/collections/new'
      fullPath: '/collections/new'
      preLoaderRoute: typeof PagesCollectionsNewRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/collections/$reference': {
      id: '/_pages/collections/$reference'
      path: '/collections/$reference'
      fullPath: '/collections/$reference'
      preLoaderRoute: typeof PagesCollectionsReferenceRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/characters/$slug': {
      id: '/_pages/characters/$slug'
      path: '/characters/$slug'
      fullPath: '/characters/$slug'
      preLoaderRoute: typeof PagesCharactersSlugRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/articles/new': {
      id: '/_pages/articles/new'
      path: '/articles/new'
      fullPath: '/articles/new'
      preLoaderRoute: typeof PagesArticlesNewRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/articles/$slug': {
      id: '/_pages/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof PagesArticlesSlugRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/anime/$slug': {
      id: '/_pages/anime/$slug'
      path: '/anime/$slug'
      fullPath: '/anime/$slug'
      preLoaderRoute: typeof PagesAnimeSlugRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/_auth/signup': {
      id: '/_pages/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof PagesAuthSignupRouteImport
      parentRoute: typeof PagesAuthRoute
    }
    '/_pages/_auth/reset': {
      id: '/_pages/_auth/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof PagesAuthResetRouteImport
      parentRoute: typeof PagesAuthRoute
    }
    '/_pages/_auth/login': {
      id: '/_pages/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PagesAuthLoginRouteImport
      parentRoute: typeof PagesAuthRoute
    }
    '/_pages/u/$username/': {
      id: '/_pages/u/$username/'
      path: '/'
      fullPath: '/u/$username/'
      preLoaderRoute: typeof PagesUUsernameIndexRouteImport
      parentRoute: typeof PagesUUsernameRoute
    }
    '/_pages/people/$slug/': {
      id: '/_pages/people/$slug/'
      path: '/'
      fullPath: '/people/$slug/'
      preLoaderRoute: typeof PagesPeopleSlugIndexRouteImport
      parentRoute: typeof PagesPeopleSlugRoute
    }
    '/_pages/novel/$slug/': {
      id: '/_pages/novel/$slug/'
      path: '/'
      fullPath: '/novel/$slug/'
      preLoaderRoute: typeof PagesNovelSlugIndexRouteImport
      parentRoute: typeof PagesNovelSlugRoute
    }
    '/_pages/manga/$slug/': {
      id: '/_pages/manga/$slug/'
      path: '/'
      fullPath: '/manga/$slug/'
      preLoaderRoute: typeof PagesMangaSlugIndexRouteImport
      parentRoute: typeof PagesMangaSlugRoute
    }
    '/_pages/edit/$editId/': {
      id: '/_pages/edit/$editId/'
      path: '/'
      fullPath: '/edit/$editId/'
      preLoaderRoute: typeof PagesEditEditIdIndexRouteImport
      parentRoute: typeof PagesEditEditIdRoute
    }
    '/_pages/collections/$reference/': {
      id: '/_pages/collections/$reference/'
      path: '/'
      fullPath: '/collections/$reference/'
      preLoaderRoute: typeof PagesCollectionsReferenceIndexRouteImport
      parentRoute: typeof PagesCollectionsReferenceRoute
    }
    '/_pages/characters/$slug/': {
      id: '/_pages/characters/$slug/'
      path: '/'
      fullPath: '/characters/$slug/'
      preLoaderRoute: typeof PagesCharactersSlugIndexRouteImport
      parentRoute: typeof PagesCharactersSlugRoute
    }
    '/_pages/articles/$slug/': {
      id: '/_pages/articles/$slug/'
      path: '/'
      fullPath: '/articles/$slug/'
      preLoaderRoute: typeof PagesArticlesSlugIndexRouteImport
      parentRoute: typeof PagesArticlesSlugRoute
    }
    '/_pages/anime/$slug/': {
      id: '/_pages/anime/$slug/'
      path: '/'
      fullPath: '/anime/$slug/'
      preLoaderRoute: typeof PagesAnimeSlugIndexRouteImport
      parentRoute: typeof PagesAnimeSlugRoute
    }
    '/_pages/u/$username/list': {
      id: '/_pages/u/$username/list'
      path: '/list'
      fullPath: '/u/$username/list'
      preLoaderRoute: typeof PagesUUsernameListRouteImport
      parentRoute: typeof PagesUUsernameRoute
    }
    '/_pages/u/$username/history': {
      id: '/_pages/u/$username/history'
      path: '/history'
      fullPath: '/u/$username/history'
      preLoaderRoute: typeof PagesUUsernameHistoryRouteImport
      parentRoute: typeof PagesUUsernameRoute
    }
    '/_pages/u/$username/favorites': {
      id: '/_pages/u/$username/favorites'
      path: '/favorites'
      fullPath: '/u/$username/favorites'
      preLoaderRoute: typeof PagesUUsernameFavoritesRouteImport
      parentRoute: typeof PagesUUsernameRoute
    }
    '/_pages/people/$slug/novel': {
      id: '/_pages/people/$slug/novel'
      path: '/novel'
      fullPath: '/people/$slug/novel'
      preLoaderRoute: typeof PagesPeopleSlugNovelRouteImport
      parentRoute: typeof PagesPeopleSlugRoute
    }
    '/_pages/people/$slug/manga': {
      id: '/_pages/people/$slug/manga'
      path: '/manga'
      fullPath: '/people/$slug/manga'
      preLoaderRoute: typeof PagesPeopleSlugMangaRouteImport
      parentRoute: typeof PagesPeopleSlugRoute
    }
    '/_pages/people/$slug/characters': {
      id: '/_pages/people/$slug/characters'
      path: '/characters'
      fullPath: '/people/$slug/characters'
      preLoaderRoute: typeof PagesPeopleSlugCharactersRouteImport
      parentRoute: typeof PagesPeopleSlugRoute
    }
    '/_pages/people/$slug/anime': {
      id: '/_pages/people/$slug/anime'
      path: '/anime'
      fullPath: '/people/$slug/anime'
      preLoaderRoute: typeof PagesPeopleSlugAnimeRouteImport
      parentRoute: typeof PagesPeopleSlugRoute
    }
    '/_pages/novel/$slug/staff': {
      id: '/_pages/novel/$slug/staff'
      path: '/staff'
      fullPath: '/novel/$slug/staff'
      preLoaderRoute: typeof PagesNovelSlugStaffRouteImport
      parentRoute: typeof PagesNovelSlugRoute
    }
    '/_pages/novel/$slug/franchise': {
      id: '/_pages/novel/$slug/franchise'
      path: '/franchise'
      fullPath: '/novel/$slug/franchise'
      preLoaderRoute: typeof PagesNovelSlugFranchiseRouteImport
      parentRoute: typeof PagesNovelSlugRoute
    }
    '/_pages/novel/$slug/characters': {
      id: '/_pages/novel/$slug/characters'
      path: '/characters'
      fullPath: '/novel/$slug/characters'
      preLoaderRoute: typeof PagesNovelSlugCharactersRouteImport
      parentRoute: typeof PagesNovelSlugRoute
    }
    '/_pages/manga/$slug/staff': {
      id: '/_pages/manga/$slug/staff'
      path: '/staff'
      fullPath: '/manga/$slug/staff'
      preLoaderRoute: typeof PagesMangaSlugStaffRouteImport
      parentRoute: typeof PagesMangaSlugRoute
    }
    '/_pages/manga/$slug/franchise': {
      id: '/_pages/manga/$slug/franchise'
      path: '/franchise'
      fullPath: '/manga/$slug/franchise'
      preLoaderRoute: typeof PagesMangaSlugFranchiseRouteImport
      parentRoute: typeof PagesMangaSlugRoute
    }
    '/_pages/manga/$slug/characters': {
      id: '/_pages/manga/$slug/characters'
      path: '/characters'
      fullPath: '/manga/$slug/characters'
      preLoaderRoute: typeof PagesMangaSlugCharactersRouteImport
      parentRoute: typeof PagesMangaSlugRoute
    }
    '/_pages/edit/$editId/update': {
      id: '/_pages/edit/$editId/update'
      path: '/update'
      fullPath: '/edit/$editId/update'
      preLoaderRoute: typeof PagesEditEditIdUpdateRouteImport
      parentRoute: typeof PagesEditEditIdRoute
    }
    '/_pages/collections/$reference/update': {
      id: '/_pages/collections/$reference/update'
      path: '/update'
      fullPath: '/collections/$reference/update'
      preLoaderRoute: typeof PagesCollectionsReferenceUpdateRouteImport
      parentRoute: typeof PagesCollectionsReferenceRoute
    }
    '/_pages/characters/$slug/voices': {
      id: '/_pages/characters/$slug/voices'
      path: '/voices'
      fullPath: '/characters/$slug/voices'
      preLoaderRoute: typeof PagesCharactersSlugVoicesRouteImport
      parentRoute: typeof PagesCharactersSlugRoute
    }
    '/_pages/characters/$slug/novel': {
      id: '/_pages/characters/$slug/novel'
      path: '/novel'
      fullPath: '/characters/$slug/novel'
      preLoaderRoute: typeof PagesCharactersSlugNovelRouteImport
      parentRoute: typeof PagesCharactersSlugRoute
    }
    '/_pages/characters/$slug/manga': {
      id: '/_pages/characters/$slug/manga'
      path: '/manga'
      fullPath: '/characters/$slug/manga'
      preLoaderRoute: typeof PagesCharactersSlugMangaRouteImport
      parentRoute: typeof PagesCharactersSlugRoute
    }
    '/_pages/characters/$slug/anime': {
      id: '/_pages/characters/$slug/anime'
      path: '/anime'
      fullPath: '/characters/$slug/anime'
      preLoaderRoute: typeof PagesCharactersSlugAnimeRouteImport
      parentRoute: typeof PagesCharactersSlugRoute
    }
    '/_pages/articles/$slug/update': {
      id: '/_pages/articles/$slug/update'
      path: '/update'
      fullPath: '/articles/$slug/update'
      preLoaderRoute: typeof PagesArticlesSlugUpdateRouteImport
      parentRoute: typeof PagesArticlesSlugRoute
    }
    '/_pages/anime/$slug/staff': {
      id: '/_pages/anime/$slug/staff'
      path: '/staff'
      fullPath: '/anime/$slug/staff'
      preLoaderRoute: typeof PagesAnimeSlugStaffRouteImport
      parentRoute: typeof PagesAnimeSlugRoute
    }
    '/_pages/anime/$slug/media': {
      id: '/_pages/anime/$slug/media'
      path: '/media'
      fullPath: '/anime/$slug/media'
      preLoaderRoute: typeof PagesAnimeSlugMediaRouteImport
      parentRoute: typeof PagesAnimeSlugRoute
    }
    '/_pages/anime/$slug/franchise': {
      id: '/_pages/anime/$slug/franchise'
      path: '/franchise'
      fullPath: '/anime/$slug/franchise'
      preLoaderRoute: typeof PagesAnimeSlugFranchiseRouteImport
      parentRoute: typeof PagesAnimeSlugRoute
    }
    '/_pages/anime/$slug/characters': {
      id: '/_pages/anime/$slug/characters'
      path: '/characters'
      fullPath: '/anime/$slug/characters'
      preLoaderRoute: typeof PagesAnimeSlugCharactersRouteImport
      parentRoute: typeof PagesAnimeSlugRoute
    }
    '/_pages/_auth/reset_/$token': {
      id: '/_pages/_auth/reset_/$token'
      path: '/reset/$token'
      fullPath: '/reset/$token'
      preLoaderRoute: typeof PagesAuthResetTokenRouteImport
      parentRoute: typeof PagesAuthRoute
    }
    '/_pages/u/$username/list/': {
      id: '/_pages/u/$username/list/'
      path: '/'
      fullPath: '/u/$username/list/'
      preLoaderRoute: typeof PagesUUsernameListIndexRouteImport
      parentRoute: typeof PagesUUsernameListRoute
    }
    '/_pages/comments/$content_type/$slug/': {
      id: '/_pages/comments/$content_type/$slug/'
      path: '/comments/$content_type/$slug'
      fullPath: '/comments/$content_type/$slug/'
      preLoaderRoute: typeof PagesCommentsContent_typeSlugIndexRouteImport
      parentRoute: typeof PagesRoute
    }
    '/_pages/u/$username/list/$content_type': {
      id: '/_pages/u/$username/list/$content_type'
      path: '/$content_type'
      fullPath: '/u/$username/list/$content_type'
      preLoaderRoute: typeof PagesUUsernameListContent_typeRouteImport
      parentRoute: typeof PagesUUsernameListRoute
    }
    '/_pages/comments/$content_type/$slug/$': {
      id: '/_pages/comments/$content_type/$slug/$'
      path: '/comments/$content_type/$slug/$'
      fullPath: '/comments/$content_type/$slug/$'
      preLoaderRoute: typeof PagesCommentsContent_typeSlugSplatRouteImport
      parentRoute: typeof PagesRoute
    }
  }
}

interface PagesAuthRouteChildren {
  PagesAuthLoginRoute: typeof PagesAuthLoginRoute
  PagesAuthResetRoute: typeof PagesAuthResetRoute
  PagesAuthSignupRoute: typeof PagesAuthSignupRoute
  PagesAuthResetTokenRoute: typeof PagesAuthResetTokenRoute
}

const PagesAuthRouteChildren: PagesAuthRouteChildren = {
  PagesAuthLoginRoute: PagesAuthLoginRoute,
  PagesAuthResetRoute: PagesAuthResetRoute,
  PagesAuthSignupRoute: PagesAuthSignupRoute,
  PagesAuthResetTokenRoute: PagesAuthResetTokenRoute,
}

const PagesAuthRouteWithChildren = PagesAuthRoute._addFileChildren(
  PagesAuthRouteChildren,
)

interface PagesSettingsRouteChildren {
  PagesSettingsApplicationsRoute: typeof PagesSettingsApplicationsRoute
  PagesSettingsCustomizationRoute: typeof PagesSettingsCustomizationRoute
  PagesSettingsListRoute: typeof PagesSettingsListRoute
  PagesSettingsNotificationsRoute: typeof PagesSettingsNotificationsRoute
  PagesSettingsProfileRoute: typeof PagesSettingsProfileRoute
  PagesSettingsSecurityRoute: typeof PagesSettingsSecurityRoute
  PagesSettingsIndexRoute: typeof PagesSettingsIndexRoute
}

const PagesSettingsRouteChildren: PagesSettingsRouteChildren = {
  PagesSettingsApplicationsRoute: PagesSettingsApplicationsRoute,
  PagesSettingsCustomizationRoute: PagesSettingsCustomizationRoute,
  PagesSettingsListRoute: PagesSettingsListRoute,
  PagesSettingsNotificationsRoute: PagesSettingsNotificationsRoute,
  PagesSettingsProfileRoute: PagesSettingsProfileRoute,
  PagesSettingsSecurityRoute: PagesSettingsSecurityRoute,
  PagesSettingsIndexRoute: PagesSettingsIndexRoute,
}

const PagesSettingsRouteWithChildren = PagesSettingsRoute._addFileChildren(
  PagesSettingsRouteChildren,
)

interface PagesAnimeSlugRouteChildren {
  PagesAnimeSlugCharactersRoute: typeof PagesAnimeSlugCharactersRoute
  PagesAnimeSlugFranchiseRoute: typeof PagesAnimeSlugFranchiseRoute
  PagesAnimeSlugMediaRoute: typeof PagesAnimeSlugMediaRoute
  PagesAnimeSlugStaffRoute: typeof PagesAnimeSlugStaffRoute
  PagesAnimeSlugIndexRoute: typeof PagesAnimeSlugIndexRoute
}

const PagesAnimeSlugRouteChildren: PagesAnimeSlugRouteChildren = {
  PagesAnimeSlugCharactersRoute: PagesAnimeSlugCharactersRoute,
  PagesAnimeSlugFranchiseRoute: PagesAnimeSlugFranchiseRoute,
  PagesAnimeSlugMediaRoute: PagesAnimeSlugMediaRoute,
  PagesAnimeSlugStaffRoute: PagesAnimeSlugStaffRoute,
  PagesAnimeSlugIndexRoute: PagesAnimeSlugIndexRoute,
}

const PagesAnimeSlugRouteWithChildren = PagesAnimeSlugRoute._addFileChildren(
  PagesAnimeSlugRouteChildren,
)

interface PagesArticlesSlugRouteChildren {
  PagesArticlesSlugUpdateRoute: typeof PagesArticlesSlugUpdateRoute
  PagesArticlesSlugIndexRoute: typeof PagesArticlesSlugIndexRoute
}

const PagesArticlesSlugRouteChildren: PagesArticlesSlugRouteChildren = {
  PagesArticlesSlugUpdateRoute: PagesArticlesSlugUpdateRoute,
  PagesArticlesSlugIndexRoute: PagesArticlesSlugIndexRoute,
}

const PagesArticlesSlugRouteWithChildren =
  PagesArticlesSlugRoute._addFileChildren(PagesArticlesSlugRouteChildren)

interface PagesCharactersSlugRouteChildren {
  PagesCharactersSlugAnimeRoute: typeof PagesCharactersSlugAnimeRoute
  PagesCharactersSlugMangaRoute: typeof PagesCharactersSlugMangaRoute
  PagesCharactersSlugNovelRoute: typeof PagesCharactersSlugNovelRoute
  PagesCharactersSlugVoicesRoute: typeof PagesCharactersSlugVoicesRoute
  PagesCharactersSlugIndexRoute: typeof PagesCharactersSlugIndexRoute
}

const PagesCharactersSlugRouteChildren: PagesCharactersSlugRouteChildren = {
  PagesCharactersSlugAnimeRoute: PagesCharactersSlugAnimeRoute,
  PagesCharactersSlugMangaRoute: PagesCharactersSlugMangaRoute,
  PagesCharactersSlugNovelRoute: PagesCharactersSlugNovelRoute,
  PagesCharactersSlugVoicesRoute: PagesCharactersSlugVoicesRoute,
  PagesCharactersSlugIndexRoute: PagesCharactersSlugIndexRoute,
}

const PagesCharactersSlugRouteWithChildren =
  PagesCharactersSlugRoute._addFileChildren(PagesCharactersSlugRouteChildren)

interface PagesCollectionsReferenceRouteChildren {
  PagesCollectionsReferenceUpdateRoute: typeof PagesCollectionsReferenceUpdateRoute
  PagesCollectionsReferenceIndexRoute: typeof PagesCollectionsReferenceIndexRoute
}

const PagesCollectionsReferenceRouteChildren: PagesCollectionsReferenceRouteChildren =
  {
    PagesCollectionsReferenceUpdateRoute: PagesCollectionsReferenceUpdateRoute,
    PagesCollectionsReferenceIndexRoute: PagesCollectionsReferenceIndexRoute,
  }

const PagesCollectionsReferenceRouteWithChildren =
  PagesCollectionsReferenceRoute._addFileChildren(
    PagesCollectionsReferenceRouteChildren,
  )

interface PagesEditEditIdRouteChildren {
  PagesEditEditIdUpdateRoute: typeof PagesEditEditIdUpdateRoute
  PagesEditEditIdIndexRoute: typeof PagesEditEditIdIndexRoute
}

const PagesEditEditIdRouteChildren: PagesEditEditIdRouteChildren = {
  PagesEditEditIdUpdateRoute: PagesEditEditIdUpdateRoute,
  PagesEditEditIdIndexRoute: PagesEditEditIdIndexRoute,
}

const PagesEditEditIdRouteWithChildren = PagesEditEditIdRoute._addFileChildren(
  PagesEditEditIdRouteChildren,
)

interface PagesMangaSlugRouteChildren {
  PagesMangaSlugCharactersRoute: typeof PagesMangaSlugCharactersRoute
  PagesMangaSlugFranchiseRoute: typeof PagesMangaSlugFranchiseRoute
  PagesMangaSlugStaffRoute: typeof PagesMangaSlugStaffRoute
  PagesMangaSlugIndexRoute: typeof PagesMangaSlugIndexRoute
}

const PagesMangaSlugRouteChildren: PagesMangaSlugRouteChildren = {
  PagesMangaSlugCharactersRoute: PagesMangaSlugCharactersRoute,
  PagesMangaSlugFranchiseRoute: PagesMangaSlugFranchiseRoute,
  PagesMangaSlugStaffRoute: PagesMangaSlugStaffRoute,
  PagesMangaSlugIndexRoute: PagesMangaSlugIndexRoute,
}

const PagesMangaSlugRouteWithChildren = PagesMangaSlugRoute._addFileChildren(
  PagesMangaSlugRouteChildren,
)

interface PagesNovelSlugRouteChildren {
  PagesNovelSlugCharactersRoute: typeof PagesNovelSlugCharactersRoute
  PagesNovelSlugFranchiseRoute: typeof PagesNovelSlugFranchiseRoute
  PagesNovelSlugStaffRoute: typeof PagesNovelSlugStaffRoute
  PagesNovelSlugIndexRoute: typeof PagesNovelSlugIndexRoute
}

const PagesNovelSlugRouteChildren: PagesNovelSlugRouteChildren = {
  PagesNovelSlugCharactersRoute: PagesNovelSlugCharactersRoute,
  PagesNovelSlugFranchiseRoute: PagesNovelSlugFranchiseRoute,
  PagesNovelSlugStaffRoute: PagesNovelSlugStaffRoute,
  PagesNovelSlugIndexRoute: PagesNovelSlugIndexRoute,
}

const PagesNovelSlugRouteWithChildren = PagesNovelSlugRoute._addFileChildren(
  PagesNovelSlugRouteChildren,
)

interface PagesPeopleSlugRouteChildren {
  PagesPeopleSlugAnimeRoute: typeof PagesPeopleSlugAnimeRoute
  PagesPeopleSlugCharactersRoute: typeof PagesPeopleSlugCharactersRoute
  PagesPeopleSlugMangaRoute: typeof PagesPeopleSlugMangaRoute
  PagesPeopleSlugNovelRoute: typeof PagesPeopleSlugNovelRoute
  PagesPeopleSlugIndexRoute: typeof PagesPeopleSlugIndexRoute
}

const PagesPeopleSlugRouteChildren: PagesPeopleSlugRouteChildren = {
  PagesPeopleSlugAnimeRoute: PagesPeopleSlugAnimeRoute,
  PagesPeopleSlugCharactersRoute: PagesPeopleSlugCharactersRoute,
  PagesPeopleSlugMangaRoute: PagesPeopleSlugMangaRoute,
  PagesPeopleSlugNovelRoute: PagesPeopleSlugNovelRoute,
  PagesPeopleSlugIndexRoute: PagesPeopleSlugIndexRoute,
}

const PagesPeopleSlugRouteWithChildren = PagesPeopleSlugRoute._addFileChildren(
  PagesPeopleSlugRouteChildren,
)

interface PagesUUsernameListRouteChildren {
  PagesUUsernameListContent_typeRoute: typeof PagesUUsernameListContent_typeRoute
  PagesUUsernameListIndexRoute: typeof PagesUUsernameListIndexRoute
}

const PagesUUsernameListRouteChildren: PagesUUsernameListRouteChildren = {
  PagesUUsernameListContent_typeRoute: PagesUUsernameListContent_typeRoute,
  PagesUUsernameListIndexRoute: PagesUUsernameListIndexRoute,
}

const PagesUUsernameListRouteWithChildren =
  PagesUUsernameListRoute._addFileChildren(PagesUUsernameListRouteChildren)

interface PagesUUsernameRouteChildren {
  PagesUUsernameFavoritesRoute: typeof PagesUUsernameFavoritesRoute
  PagesUUsernameHistoryRoute: typeof PagesUUsernameHistoryRoute
  PagesUUsernameListRoute: typeof PagesUUsernameListRouteWithChildren
  PagesUUsernameIndexRoute: typeof PagesUUsernameIndexRoute
}

const PagesUUsernameRouteChildren: PagesUUsernameRouteChildren = {
  PagesUUsernameFavoritesRoute: PagesUUsernameFavoritesRoute,
  PagesUUsernameHistoryRoute: PagesUUsernameHistoryRoute,
  PagesUUsernameListRoute: PagesUUsernameListRouteWithChildren,
  PagesUUsernameIndexRoute: PagesUUsernameIndexRoute,
}

const PagesUUsernameRouteWithChildren = PagesUUsernameRoute._addFileChildren(
  PagesUUsernameRouteChildren,
)

interface PagesRouteChildren {
  PagesAuthRoute: typeof PagesAuthRouteWithChildren
  PagesOauthRoute: typeof PagesOauthRoute
  PagesScheduleRoute: typeof PagesScheduleRoute
  PagesSettingsRoute: typeof PagesSettingsRouteWithChildren
  PagesIndexRoute: typeof PagesIndexRoute
  PagesAnimeSlugRoute: typeof PagesAnimeSlugRouteWithChildren
  PagesArticlesSlugRoute: typeof PagesArticlesSlugRouteWithChildren
  PagesArticlesNewRoute: typeof PagesArticlesNewRoute
  PagesCharactersSlugRoute: typeof PagesCharactersSlugRouteWithChildren
  PagesCollectionsReferenceRoute: typeof PagesCollectionsReferenceRouteWithChildren
  PagesCollectionsNewRoute: typeof PagesCollectionsNewRoute
  PagesCommentsLatestRoute: typeof PagesCommentsLatestRoute
  PagesEditEditIdRoute: typeof PagesEditEditIdRouteWithChildren
  PagesEditContentRoute: typeof PagesEditContentRoute
  PagesEditNewRoute: typeof PagesEditNewRoute
  PagesMangaSlugRoute: typeof PagesMangaSlugRouteWithChildren
  PagesNovelSlugRoute: typeof PagesNovelSlugRouteWithChildren
  PagesPeopleSlugRoute: typeof PagesPeopleSlugRouteWithChildren
  PagesUUsernameRoute: typeof PagesUUsernameRouteWithChildren
  PagesAnimeIndexRoute: typeof PagesAnimeIndexRoute
  PagesArticlesIndexRoute: typeof PagesArticlesIndexRoute
  PagesCharactersIndexRoute: typeof PagesCharactersIndexRoute
  PagesCollectionsIndexRoute: typeof PagesCollectionsIndexRoute
  PagesEditIndexRoute: typeof PagesEditIndexRoute
  PagesMangaIndexRoute: typeof PagesMangaIndexRoute
  PagesNovelIndexRoute: typeof PagesNovelIndexRoute
  PagesPeopleIndexRoute: typeof PagesPeopleIndexRoute
  PagesCommentsContent_typeSlugSplatRoute: typeof PagesCommentsContent_typeSlugSplatRoute
  PagesCommentsContent_typeSlugIndexRoute: typeof PagesCommentsContent_typeSlugIndexRoute
}

const PagesRouteChildren: PagesRouteChildren = {
  PagesAuthRoute: PagesAuthRouteWithChildren,
  PagesOauthRoute: PagesOauthRoute,
  PagesScheduleRoute: PagesScheduleRoute,
  PagesSettingsRoute: PagesSettingsRouteWithChildren,
  PagesIndexRoute: PagesIndexRoute,
  PagesAnimeSlugRoute: PagesAnimeSlugRouteWithChildren,
  PagesArticlesSlugRoute: PagesArticlesSlugRouteWithChildren,
  PagesArticlesNewRoute: PagesArticlesNewRoute,
  PagesCharactersSlugRoute: PagesCharactersSlugRouteWithChildren,
  PagesCollectionsReferenceRoute: PagesCollectionsReferenceRouteWithChildren,
  PagesCollectionsNewRoute: PagesCollectionsNewRoute,
  PagesCommentsLatestRoute: PagesCommentsLatestRoute,
  PagesEditEditIdRoute: PagesEditEditIdRouteWithChildren,
  PagesEditContentRoute: PagesEditContentRoute,
  PagesEditNewRoute: PagesEditNewRoute,
  PagesMangaSlugRoute: PagesMangaSlugRouteWithChildren,
  PagesNovelSlugRoute: PagesNovelSlugRouteWithChildren,
  PagesPeopleSlugRoute: PagesPeopleSlugRouteWithChildren,
  PagesUUsernameRoute: PagesUUsernameRouteWithChildren,
  PagesAnimeIndexRoute: PagesAnimeIndexRoute,
  PagesArticlesIndexRoute: PagesArticlesIndexRoute,
  PagesCharactersIndexRoute: PagesCharactersIndexRoute,
  PagesCollectionsIndexRoute: PagesCollectionsIndexRoute,
  PagesEditIndexRoute: PagesEditIndexRoute,
  PagesMangaIndexRoute: PagesMangaIndexRoute,
  PagesNovelIndexRoute: PagesNovelIndexRoute,
  PagesPeopleIndexRoute: PagesPeopleIndexRoute,
  PagesCommentsContent_typeSlugSplatRoute:
    PagesCommentsContent_typeSlugSplatRoute,
  PagesCommentsContent_typeSlugIndexRoute:
    PagesCommentsContent_typeSlugIndexRoute,
}

const PagesRouteWithChildren = PagesRoute._addFileChildren(PagesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PagesRoute: PagesRouteWithChildren,
  AuthGoogleRoute: AuthGoogleRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  ApiOgAnimeRoute: ApiOgAnimeRoute,
  ApiOgMangaRoute: ApiOgMangaRoute,
  ApiOgNovelRoute: ApiOgNovelRoute,
  ApiSitemapAnimeRoute: ApiSitemapAnimeRoute,
  ApiSitemapMangaRoute: ApiSitemapMangaRoute,
  ApiSitemapNovelRoute: ApiSitemapNovelRoute,
  AuthActivateTokenRoute: AuthActivateTokenRoute,
  AuthResetTokenRoute: AuthResetTokenRoute,
  ApiSitemapIndexRoute: ApiSitemapIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
