export const API_LIMITS = {
    username: { min: 5, max: 64 },
    password: { min: 8, max: 256 },
    clientName: { min: 3, max: 128 },
    clientDescription: { min: 3, max: 512 },
    profileDescription: { max: 140 },
    listNote: { max: 2048 },
    listProgress: { max: 10000 },
    listRepeats: { max: 100 },
    listScore: { min: 0, max: 10 },
    commentText: { min: 1, max: 2048 },
    articleTitle: { min: 3, max: 255 },
    collectionTitle: { min: 3, max: 255 },
    collectionDescription: { min: 3, max: 65536 },
    tags: { max: 3 },
    searchQuery: { min: 2, max: 255 },
    userSearchQuery: { min: 3, max: 255 },
    pageSize: { min: 1, max: 100 },
    oklch: {
        l: { min: 0, max: 1 },
        c: { min: 0, max: 0.4 },
        h: { min: 0, max: 360 },
    },
} as const;
