/** Converts text between Ukrainian (ЙЦУКЕН) and English (QWERTY) keyboard layouts. */

export enum KeyboardLayoutEnum {
    EN = 'en',
    UK = 'uk',
    MIXED = 'mixed',
}

// Pre-compiled regexes for layout detection
const EN_CHAR_REGEX = /[a-zA-Z]/;
const UK_CHAR_REGEX = /[а-яА-ЯіІїЇєЄґҐ]/;

// Vowel regexes for heuristic detection
const EN_VOWEL_REGEX = /[aeiouAEIOU]/g;
const UK_VOWEL_REGEX = /[аеиіїоуєюяАЕИІЇОУЄЮЯ]/g;

// Converted text must have at least this much better vowel ratio to trigger conversion
const MIN_VOWEL_IMPROVEMENT = 0.1;

/**
 * Character mapping from English (QWERTY) to Ukrainian (ЙЦУКЕН) keyboard layout
 * Based on physical key positions
 */
const EN_TO_UK_MAP: Record<string, string> = {
    // Lowercase
    q: 'й',
    w: 'ц',
    e: 'у',
    r: 'к',
    t: 'е',
    y: 'н',
    u: 'г',
    i: 'ш',
    o: 'щ',
    p: 'з',
    '[': 'х',
    ']': 'ї',
    a: 'ф',
    s: 'і',
    d: 'в',
    f: 'а',
    g: 'п',
    h: 'р',
    j: 'о',
    k: 'л',
    l: 'д',
    ';': 'ж',
    "'": 'є',
    z: 'я',
    x: 'ч',
    c: 'с',
    v: 'м',
    b: 'и',
    n: 'т',
    m: 'ь',
    ',': 'б',
    '.': 'ю',
    '/': '.',
    '`': 'ґ',
    // Uppercase
    Q: 'Й',
    W: 'Ц',
    E: 'У',
    R: 'К',
    T: 'Е',
    Y: 'Н',
    U: 'Г',
    I: 'Ш',
    O: 'Щ',
    P: 'З',
    '{': 'Х',
    '}': 'Ї',
    A: 'Ф',
    S: 'І',
    D: 'В',
    F: 'А',
    G: 'П',
    H: 'Р',
    J: 'О',
    K: 'Л',
    L: 'Д',
    ':': 'Ж',
    '"': 'Є',
    Z: 'Я',
    X: 'Ч',
    C: 'С',
    V: 'М',
    B: 'И',
    N: 'Т',
    M: 'Ь',
    '<': 'Б',
    '>': 'Ю',
    '?': ',',
    '~': 'Ґ',
};

/**
 * Character mapping from Ukrainian (ЙЦУКЕН) to English (QWERTY) keyboard layout
 * Generated by reversing the EN_TO_UK_MAP
 */
const UK_TO_EN_MAP: Record<string, string> = Object.fromEntries(
    Object.entries(EN_TO_UK_MAP).map(([en, uk]) => [uk, en]),
);

/**
 * Detects the keyboard layout of text using single-pass detection with early exit.
 *
 * @param text - Text to analyze
 * @returns Detected keyboard layout (EN, UK, or MIXED)
 *
 * @example
 * detectLayout('hello')         // KeyboardLayoutEnum.EN
 * detectLayout('привіт')        // KeyboardLayoutEnum.UK
 * detectLayout('hello привіт')  // KeyboardLayoutEnum.MIXED
 * detectLayout('123')           // KeyboardLayoutEnum.MIXED (no letters)
 */
export function detectLayout(text: string): KeyboardLayoutEnum {
    let hasEn = false;
    let hasUk = false;

    for (const char of text) {
        if (!hasEn && EN_CHAR_REGEX.test(char)) hasEn = true;
        if (!hasUk && UK_CHAR_REGEX.test(char)) hasUk = true;

        if (hasEn && hasUk) return KeyboardLayoutEnum.MIXED;
    }

    if (hasEn) return KeyboardLayoutEnum.EN;
    if (hasUk) return KeyboardLayoutEnum.UK;

    return KeyboardLayoutEnum.MIXED;
}

/**
 * Converts text from English to Ukrainian keyboard layout.
 *
 * @param text - Text typed with English keyboard layout
 * @returns Text converted to Ukrainian layout
 *
 * @example
 * convertEnToUk('ghbdsn') // 'привіт'
 */
export function convertEnToUk(text: string): string {
    return text
        .split('')
        .map((char) => EN_TO_UK_MAP[char] ?? char)
        .join('');
}

/**
 * Converts text from Ukrainian to English keyboard layout.
 *
 * @param text - Text typed with Ukrainian keyboard layout
 * @returns Text converted to English layout
 *
 * @example
 * convertUkToEn('рудущ') // 'hello'
 */
export function convertUkToEn(text: string): string {
    return text
        .split('')
        .map((char) => UK_TO_EN_MAP[char] ?? char)
        .join('');
}

/**
 * Calculates vowel ratio in text for a given language.
 */
function getVowelRatio(text: string, vowelRegex: RegExp): number {
    const letters = text.replace(/[^a-zA-Zа-яА-ЯіІїЇєЄґҐ]/g, '');
    if (letters.length === 0) return 0;

    const vowels = text.match(vowelRegex)?.length ?? 0;
    return vowels / letters.length;
}

/**
 * Checks if text appears to be typed with wrong keyboard layout.
 * Compares vowel ratios: if converted text has significantly better
 * vowel distribution, it's likely the wrong layout was used.
 *
 * @param text - Text to analyze
 * @param currentLayout - Detected layout of the text
 * @returns true if text likely needs conversion
 */
function looksLikeWrongLayout(
    text: string,
    currentLayout: KeyboardLayoutEnum,
): boolean {
    if (currentLayout === KeyboardLayoutEnum.MIXED) {
        return false;
    }

    const currentVowelRatio =
        currentLayout === KeyboardLayoutEnum.EN
            ? getVowelRatio(text, EN_VOWEL_REGEX)
            : getVowelRatio(text, UK_VOWEL_REGEX);

    const converted =
        currentLayout === KeyboardLayoutEnum.EN
            ? convertEnToUk(text)
            : convertUkToEn(text);

    const convertedVowelRatio =
        currentLayout === KeyboardLayoutEnum.EN
            ? getVowelRatio(converted, UK_VOWEL_REGEX)
            : getVowelRatio(converted, EN_VOWEL_REGEX);

    return convertedVowelRatio - currentVowelRatio >= MIN_VOWEL_IMPROVEMENT;
}

/**
 * Main keyboard-layout correction. Heuristically converts text typed with the
 * wrong layout; returns the original if it looks valid, mixed, or letter-free.
 *
 * @example
 * convertLayout('ghbdsn') // 'привіт' (EN gibberish → UK)
 * convertLayout('naruto') // 'naruto' (valid EN, unchanged)
 */
export function convertLayout(text?: string): string | undefined {
    if (!text) return undefined;

    const currentLayout = detectLayout(text);

    if (currentLayout === KeyboardLayoutEnum.MIXED) {
        return text;
    }

    if (!looksLikeWrongLayout(text, currentLayout)) {
        return text;
    }

    if (currentLayout === KeyboardLayoutEnum.EN) {
        return convertEnToUk(text);
    }

    return convertUkToEn(text);
}
